# configs/config.yaml
defaults:
  - paths: local
  - hydra: base
  - utility_functions: base
  - logging_utils: base
  - io_policy: base
  - model_params: base
  - ml_experiments: base
  - test_params: base
  - tests: base
  - data_split: base
  - transformations: base
  - datasets: cmapss_ds02_006
  - data_versions: base
  - data_storage: base
  - pipeline: orchestrate_dvc_flow
  - _self_

cmd_python: "$CMD_PYTHON"

universal_step_script: "scripts/universal_step.py"
dvc_default_desc: "Refer to deps/outs for details."

# hardcode random_state
rng_seed: 42

# dynamically generated unique run identifier
run_id_outputs: ${now:%Y%m%d_%H%M%S}
