defaults:
  - base
  - _self_

split: train
suffix: '_dev'
# File paths input data
input_file_path: ${paths.directories.data}/${datasets.dataset.directory_name}/${data_versions.data_version_input}/${data_versions.data_version_input}_${.split}.${data_storage.input_file_extension}

input_metadata_file_path: ${paths.directories.data}/${datasets.dataset.directory_name}/${data_versions.data_version_input}/${data_versions.data_version_input}_${.split}_metadata.${data_storage.input_metadata_file_extension}

# File paths output data
output_file_path: ${paths.directories.data}/${datasets.dataset.directory_name}/${data_versions.data_version_output}/${data_versions.data_version_output}_${.split}.${data_storage.output_file_extension}

output_metadata_file_path: ${paths.directories.data}/${datasets.dataset.directory_name}/${data_versions.data_version_output}/${data_versions.data_version_output}_${.split}_metadata.${data_storage.output_metadata_file_extension}
