dataset:
  directory_name: "cmapss_ds02_006"
  name: "N-CMAPSS_DS02-006"
  filename: "${.name}.h5"
  original_file_path: "/Volumes/data/predictive_maintenance/nasa_turbofan_degradation_v2/cmapss2_complete/data_set/${.filename}"
  tables:
  - name: W
    desc: ""
    parts:
    - W_dev
    - W_test
    - W_var
  - name: X_s
    desc: ""
    parts:
    - X_s_dev
    - X_s_test
    - X_s_var
  - name: X_v
    desc: ""
    parts:
    - X_v_dev
    - X_v_test
    - X_v_var
  - name: T
    desc: ""
    parts:
    - T_dev
    - T_test
    - T_var
  - name: Y
    desc: "Remaining useful life"
    parts:
    - Y_dev
    - Y_test
  - name: A
    desc: "Auxiliary data"
    parts:
    - A_dev
    - A_test
    - A_var

train_units:
- 2
- 5
- 10
- 16
- 18
- 20

test_units:
- 11
- 14
- 15
